name: Deploy Google Cloud Function

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 18
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: npm install, build
        run: |
          npm i
          npm run build

      - name: Setup gcloud environment
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          service_account_email: pyh0803@easy-wms.iam.gserviceaccount.com
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: deploy-function
        run: gcloud functions deploy cjreturn --gen2 --allow-unauthenticated --region=asia-northeast3 --runtime=nodejs18 --source=. --entry-point=hello --trigger-http --memory=2000 --run-service-account=pyh0803@easy-wms.iam.gserviceaccount.com --timeout=3600s --set-env-vars INSTANCE_UNIX_SOCKET=${{ secrets.INSTANCE_UNIX_SOCKET }},INSTANCE_CONNECTION_NAME=${{ secrets.INSTANCE_CONNECTION_NAME }},DB_NAME=${{ secrets.DB_NAME }},DB_USER=${{ secrets.DB_USER }},DB_PASS=${{ secrets.DB_PASS }},

      - name: deploy-cloud-run
        run: gcloud run services update cjreturn --add-cloudsql-instances=easy-wms:asia-northeast3:ezstorage-db-develop
